apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    app: mongo-db
  namespace: studentapi  
spec:
  selector:
    app: mongo-db
  type:  ClusterIP  
  ports:
  - name: mongo-service
    port: 27017
    targetPort: 27017

    
