apiVersion: v1
kind: Service
metadata:
  name: student-rest-service
  labels:
    app: student-deploy
  namespace: studentapi  
spec:
  type: NodePort
  selector:
    app: student-deploy
  ports:
  - name: student-service
    port: 3000
    targetPort: 3000
    nodePort: 30006
